#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

require 'pry'
class Fib
  def collector(limit, current_num=2, collection=[1])
    @collection = collection
    current = current_num
    if current < limit
      @collection << current
      current = current + @collection[-2]
      #binding.pry
      self.collector(limit, current, @collection)
    else
      @sum = 0
      @collection.each do |num|
        if num.even?
          @sum += num
        else
        end
      puts @sum
      end
    end
  end
end

f = Fib.new
f.collector(4000000)